CREATE TABLE Person(
	Id INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nickname NVARCHAR UNIQUE NOT NULL,
	FirstName NVARCHAR NULL,
	EMail VARCHAR(30) NULL,
	[Password] VARBINARY NOT NULL,
	Picture IMAGE NULL
);

--ALTER TABLE Person ALTER COLUMN Nickname NVARCHAR(200);
ALTER TABLE Person ALTER COLUMN [Password] VARBINARY(8000);

ALTER TABLE Person ADD Order_id INT REFERENCES [Order](Id)


CREATE TABLE Product(
	Id INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR NOT NULL,
	Price MONEY NOT NULL,
	Amount INT NOT NULL,
	[Description] NVARCHAR NULL,
	SIZE NVARCHAR NULL,
	CompanyName NVARCHAR NULL,
	Photo IMAGE NULL,
	[Weight] DECIMAL NULL
);

CREATE TABLE [Order](
	Id INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PersonId INT REFERENCES Person(Id),
	ProductId INT REFERENCES Product(Id),
	Amount INT NOT NULL,
	Price MONEY
);

CREATE TABLE Articles(
	Id INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PersonId INT REFERENCES Person(Id),
	Title NCHAR(150) NOT NULL,
	[Text] NVARCHAR(MAX) NOT NULL,
	Link NVARCHAR(MAX) NULL
);

INSERT INTO Person(Nickname,FirstName,EMail,[Password]) VALUES('NoName1','Дима','lana.lakutina@mail.ru',HASHBYTES('SHA2_256','12345'))
DELETE Person WHERE Id=11

CREATE TRIGGER HashPass
ON Person 
INSTEAD OF INSERT
AS
DECLARE @HashPass NVARCHAR(32);
SET @HashPass = CONVERT(NVARCHAR(32),(SELECT [Password] from inserted));
INSERT INTO Person VALUES((SELECT Nickname FROM inserted),(SELECT FirstName FROM inserted),(SELECT EMail FROM inserted),HASHBYTES('SHA2_256', @HashPass),(SELECT Picture FROM inserted),(SELECT Order_id FROM inserted))

SELECT * FROM Person

