# Generated by Django 4.0.2 on 2022-03-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to='avatars/%Y/%m/%d/')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
