# Generated by Django 4.0.2 on 2022-03-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_person_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
